### ISSUE TITLE
Should a script be run under this line?

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/DSCI_522_Forest_Fire_Analysis#27]
https://github.com/UBC-MDS/DSCI_522_Forest_Fire_Analysis/blob/fcc4411500766977a51f24163aab0ebe44cde09f/Makefile#L9

Looks like the line under this one is missing... should `Rscript scripts/clean_data.R data/forestfires.csv data/cleaned_forestfires.csv` be there?

**Comment by DavyGuo** [comment]
Yes, this line has been added.
